project:
  type: website
  output-dir: docs

website:
  navbar:
    logo: "logo.png"
    left:
      - text: "Contacto"
        href: cv.qmd

      - text: "R para el análisis de datos"
        menu:
          - text: "Sobre el libro"
            href: libro.qmd
          - text: "La Datáfora Interactiva"
            href: dataforaint.qmd

      - text: "IncoreR"
        menu:
          - text: "Sobre el paquete"
            href: intro.qmd
          - text: "Manual"
            href: Manual.qmd
          - text: "IncoreR Web"
            href: incorerweb.qmd

      - text: "Prosecnur"
        menu:
          - text: "Sobre el paquete"
            href: prosecnur.qmd
          - text: "Manual"
            href: Guia_Prosecnur.qmd

format:
  html:
    theme: cosmo
    css: estetica.css
    toc: false
    smooth-scroll: true
  