project:
  type: website
  output-dir: docs

website:
  navbar:
    logo: "logo.png"           
    left:
      - href: libro.qmd
        text: "Libro"

      - href: dataforaint.qmd
        text: "La Datáfora Interactiva"

      - href: main_proyectos.qmd
        text: "Proyectos"

      - text: "IncoreR"
        menu:
          - text: "Introducción al paquete"
            href: intro.qmd
          - text: "Manual para R"
            href: Manual.qmd
          - text: "IncoreR en el navegador"
            href: incorerweb.qmd
      - href: exp.qmd
        text: "Experiencia"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    toc-depth: 3
    toc-expand: true
    smooth-scroll: true
  