project:
  type: website
  output-dir: docs  

website:
  title: "La Datafora"
  navbar:
    left:
      - href: about.qmd
        text: "Sobre el proyecto"

      - href: libro.qmd
        text: "Libro"

      - href: dataforaint.qmd
        text: "La Datafora Interactiva"

      - href: main_proyectos.qmd
        text: "Proyectos"

      - text: "Paquetes"
        menu:
          - text: "Prosecnur"
            href: paquetes/prosecnur/
          - text: "IncoreR"
            href: paquetes/incorer/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-expand: true
    smooth-scroll: true