project:
  type: website
  output-dir: docs

website:
  title: "La Datáfora"
  navbar:
    logo: "logo.png"           
    left:
      - href: about.qmd
        text: "Sobre el proyecto"

      - href: libro.qmd
        text: "Libro"

      - href: dataforaint.qmd
        text: "La Datáfora Interactiva"

      - href: main_proyectos.qmd
        text: "Proyectos"

      - text: "IncoreR"
        menu:
          - text: "Introducción al paquete"
            href: incorer/intro.qmd
          - text: "Manual para R"
            href: incorer/Manual.qmd
          - text: "IncoreR en el navegador"
            href: incorer/incorerweb.qmd

      - text: "Prosecnur"
        href: prosecnur/



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-expand: true
    smooth-scroll: true
  