---
title: "IncoreR en la Web"
page-layout: full
format:
  html:
    toc: false
---

La aplicaci칩n **IncoreRWeb** permite explorar visualmente los resultados del INCORE a trav칠s de una plataforma interactiva desarrollada en Shiny. Desde la aplicaci칩n pueden consultarse puntajes e indicadores de todas las ediciones, junto con la multitud de gr치ficos que el paquete incorer ofrece.

El paquete **IncoreR** es un paquete de c칩digo abierto en R desarrollado a mediados de 2025 para facilitar la visualizaci칩n de resultados, ofreciendo una amplia variedad de gr치ficos para mostrar los indicadores y pilares del 칤ndice. Entre ellos se incluyen gr치ficos de distribuci칩n, densidad, comparaciones entre medias, mapas regionales, gr치ficos de radar, entre otros, todos con m칰ltiples opciones de personalizaci칩n.

El objetivo de **IncoreRWeb** es habilitar estas herramientas y generar gr치ficos de alta calidad **sin necesidad de manejar todas las funciones de R**. Haciendo uso del paquete, la aplicaci칩n web ofrece una interfaz interactiva que permite al usuario aplicar filtros y personalizar los gr치ficos seg칰n sus necesidades, generando as칤 las visualizaciones que desee y pudiendo posteriormente hacer uso de ellas.

```{=html}
<style>
  .btn-ldf {
    display: inline-block;
    padding: 1rem 2rem;
    background-color: var(--accent);
    color: #fff;
    font-size: 1.15rem;
    font-weight: 500;
    border-radius: 12px;
    text-decoration: none;
    box-shadow: 0 3px 8px rgba(0,0,0,.08);
    transition: all 0.25s ease-in-out;
  }
  .btn-ldf:hover {
    background-color: #a56b45;
    transform: translateY(-2px);
    box-shadow: 0 6px 12px rgba(0,0,0,0.14);
    color: #fff;
    text-decoration: none;
  }
  .btn-center {
    display: flex;
    justify-content: center;
    margin-top: 2.5rem;
    margin-bottom: 2.5rem;
  }
</style>

<div class="btn-center">
  <a class="btn-ldf" href="https://np6xsv-gonzalo-almendariz.shinyapps.io/IcorerRWeb/" target="_blank">
    游깷 Explora IncoreRWeb
  </a>
</div>
```